version: "3"
services:

  nginx:
    build:
      context: "./nginx" 
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    container_name: nginx-container
    depends_on:
      - client
      - api
    restart: always

  client:
    build:
      context: "./client"
      dockerfile: Dockerfile.dev
    stdin_open: true
    container_name: client-container
    volumes:
      - ./client:/app
    depends_on:
      - api

  api:
    build:
      context: "./server"
      dockerfile: Dockerfile
    restart: always
    container_name: server-container
    volumes:
      - ./server:/app
    env_file: 
      - ./server/.env
    depends_on:
      - db
  
  db:
    image: mongo:latest
    restart: always
    container_name: mongodb-container
    volumes:
      - dbData:/data/db
    env_file:
      - ./db/.env
      
volumes:
  dbData: {}
